### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by am174**
introduced myself

### CODE REVIEW

**Comment by Sahil-Ajmera** [comment]
You have to add me as  a reviewer before you merge it. I just commented before
See the options on the right to add me as a reviwer.

**Comment by Sahil-Ajmera** [comment]
Just saying. .. .

**Comment by Sahil-Ajmera** [comment]
I review it ,You see that i have approved the changes you made and THEN you merge it.

**Comment by am174** [comment]
Message on whatsapp and chat

Regards
Aman

**Pull request merged**
